# Default values for 5gran.
ran:
  image:
    repository: quay.io/adetalho/ueransim
    pullPolicy: Always
    tag: "v3.2.6"
  amf:
    address: 172.30.137.190
    port: 38412
  user:
    imsi: "imsi-208930000000001"
  tac: 7
