{{ if .Values.ausf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: open5gs-ausf.{{ .Release.Namespace }}.svc.cluster.local
    nrf:
     sbi:
      name: open5gs-nrf.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}