{{ if .Values.nssf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    #logger:
       #file: /var/log/open5gs/nssf.log   
    nssf:
      sbi:     
      - addr: 0.0.0.0
        advertise: open5gs-nssf.{{ .Release.Namespace }}.svc.cluster.local
      nsi:
      - addr: open5gs-nrf.{{ .Release.Namespace }}.svc.cluster.local
        port: 80
        s_nssai:
          sst: 1        
    nrf:
     sbi:
      name: open5gs-nrf.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}