# Default values for 5gcore-helm.

open5gcore:
  image:
    repository: quay.io/adetalho/open5gs
    pullPolicy: IfNotPresent
    tag: "2.4.4"

webui:
  enabled: false
  image:
    repository: docker.io/efatnar/open5gcore-webui
    pullPolicy: IfNotPresent
    tag: "v1.1"

dnn: internet  

k8s:
 interface: eth0

serviceMesh:
  enabled: false

amf:
  enabled: false
  mcc: 208
  mnc: 93
  tac: 7
ausf:
  enabled: false
mongo:
  enabled: false
nrf:
  enabled: false
  serviceName: open5gs-nrf-shared
nssf:
  enabled: false
pcf:
  enabled: false
smf:
  enabled: true
  serviceName: open5gs-smf-shared
udm:
  enabled: false
udr:
  enabled: false
upf:
  enabled: true