# Default values for 5gcore-helm.

open5gcore:
  image:
    repository: quay.io/adetalho/open5gs
    pullPolicy: Always
    tag: "2.4.4"

webui:
  enabled: true
  image:
    repository: docker.io/efatnar/open5gcore-webui
    pullPolicy: IfNotPresent
    tag: "v1.1"

dnn: internet  

k8s:
 interface: eth0

amf:
  enabled: true
  mcc: 208
  mnc: 93
  tac: 7
  serviceName: open5gs-amf-shared
bsf:
  enabled: true
ausf:
  enabled: true
mongo:
  enabled: true
nrf:
  enabled: true
  serviceName: open5gs-nrf
nssf:
  enabled: true
pcf:
  enabled: true
  serviceName: open5gs-pcf-shared
udm:
  enabled: true
  serviceName: open5gs-udm-shared
udr:
  enabled: true
upf:
  enabled: false
  serviceName: open5gs-upf
smf:
  enabled: false
  serviceName: open5gs-smf-shared